import { useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import {
  ArrowLeft,
  Smartphone,
  Globe,
  TrendingUp,
  AlertTriangle,
  Clock,
  Zap,
  Shield,
  CheckCircle2,
  XCircle,
  KeyRound,
  Edit3,
  Cpu,
  Sparkles,
  ShieldCheck,
  ShieldAlert,
  Activity,
  Inbox,
  GitBranch,
  User,
  MapPin,
  Store,
  Calendar,
  CreditCard,
  ChevronRight,
} from "lucide-react";
import RadialGauge from "@/components/RadialGauge";
import { StatusPill } from "@/components/StatusPill";
import {
  AIRiskIntelligence,
  IntelligentLLMRouting,
  PromptInjectionProtection,
  UsageTransparency,
  PredictionPipeline,
  computeAIRouting,
} from "@/components/AIRiskIntelligence";
import { getTransactionById, LLM_RECOMMENDATION } from "@/mock/data";
import { cn } from "@/lib/utils";

const ANOMALY_ICONS = {
  Smartphone,
  Globe,
  TrendingUp,
  AlertTriangle,
  Clock,
  Zap,
  Shield,
};

const PIPELINES = [
  {
    id: "A",
    title: "Pipeline A",
    label: "Low Risk · Auto-Approve",
    icon: ShieldCheck,
    accent: "#10B981",
    color: "emerald",
    steps: ["Data Transformation", "XGBoost", "Otari Selected Pipeline A", "Approved"],
  },
  {
    id: "B",
    title: "Pipeline B",
    label: "Medium Risk · OTP",
    icon: Shield,
    accent: "#F59E0B",
    color: "amber",
    steps: [
      "Data Transformation",
      "XGBoost",
      "Otari Selected Pipeline B",
      "Isolation Forest",
      "OTP Recommended",
      "Approved",
    ],
  },
  {
    id: "C",
    title: "Pipeline C",
    label: "Critical · Human Review",
    icon: ShieldAlert,
    accent: "#EF4444",
    color: "red",
    steps: [
      "Data Transformation",
      "XGBoost",
      "Otari Selected Pipeline C",
      "Isolation Forest",
      "LLM Recommendation",
      "Human Review",
      "Final Decision",
    ],
  },
];

export default function FraudAnalysis() {
  const { txId } = useParams();
  const nav = useNavigate();
  const tx = getTransactionById(txId);
  const activePipeline = PIPELINES.find((p) => p.id === tx.pipeline);
  const routing = computeAIRouting(tx);
  const [notes, setNotes] = useState("");

  return (
    <div className="mx-auto max-w-[1400px] space-y-8" data-testid="fraud-analysis-page">
      {/* Header */}
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <button
            data-testid="back-btn"
            onClick={() => nav(-1)}
            className="mb-3 inline-flex items-center gap-1.5 font-mono text-[10px] uppercase tracking-widest text-slate-500 hover:text-slate-200"
          >
            <ArrowLeft size={11} /> Back to stream
          </button>
          <div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.18em] text-purple-300">
            <Sparkles size={11} /> AI Investigation Report
          </div>
          <h1 className="mt-2 flex items-center gap-3 text-3xl font-medium tracking-tight text-white">
            <span className="font-mono">{tx.id}</span>
            <StatusPill level={tx.riskLevel}>{tx.riskLevel}</StatusPill>
          </h1>
          <p className="mt-1 text-sm text-slate-500">
            Generated by Otari Decision Engine · {new Date(tx.timestamp).toLocaleString()}
          </p>
        </div>
        <div className="flex gap-2">
          <Badge label="Confidence" value={`${tx.confidence}%`} color="emerald" />
          <Badge label="Fraud Prob." value={`${tx.fraudProb}%`} color={tx.riskLevel === "critical" ? "red" : tx.riskLevel === "medium" ? "amber" : "emerald"} />
          <Badge label="Latency" value="128ms" color="purple" />
        </div>
      </div>

      {/* Section 1: Transaction Overview */}
      <Section title="Transaction Overview" eyebrow="01 · Context" testId="section-overview">
        <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
          <OverviewItem icon={CreditCard} label="Amount" value={`$${tx.amount.toLocaleString(undefined, { minimumFractionDigits: 2 })}`} mono />
          <OverviewItem icon={User} label="Customer" value={tx.customerName} sub={tx.customerId} />
          <OverviewItem icon={Store} label="Merchant" value={tx.merchant} />
          <OverviewItem icon={MapPin} label="Location" value={`${tx.location.city}, ${tx.location.country}`} sub={tx.location.flag} />
          <OverviewItem icon={Smartphone} label="Device" value={tx.device} />
          <OverviewItem icon={Calendar} label="Timestamp" value={new Date(tx.timestamp).toLocaleString()} mono />
          <OverviewItem icon={Activity} label="Channel" value="Card-not-present · Web" />
          <OverviewItem icon={Shield} label="3D Secure" value={tx.riskLevel === "critical" ? "Bypassed" : "Authenticated"} />
        </div>
      </Section>

      {/* AI Risk Intelligence Suite */}
      <AIRiskIntelligence tx={tx} routing={routing} />
      <IntelligentLLMRouting routing={routing} />
      <PromptInjectionProtection routing={routing} />
      <UsageTransparency routing={routing} />
      <PredictionPipeline routing={routing} />

      {/* Section 2: Anomalies */}
      <Section title="Detected Behavioural Anomalies" eyebrow="02 · Signals" testId="section-anomalies">
        <div className="grid grid-cols-1 gap-3 md:grid-cols-2 lg:grid-cols-3">
          {tx.anomalies.map((a, i) => {
            const Icon = ANOMALY_ICONS[a.icon] || AlertTriangle;
            return (
              <motion.div
                key={a.key}
                initial={{ opacity: 0, y: 6 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.05 }}
                data-testid={`anomaly-${a.key}`}
                className="group rounded-lg border border-[#1E2536] bg-[#111623] p-4 transition-colors hover:border-purple-500/30 hover:bg-[#131A2A]"
              >
                <div className="flex items-start gap-3">
                  <div className="grid h-9 w-9 shrink-0 place-items-center rounded-md bg-purple-500/10 ring-1 ring-purple-500/20">
                    <Icon size={15} strokeWidth={1.6} className="text-purple-300" />
                  </div>
                  <div className="min-w-0 flex-1">
                    <div className="text-sm font-medium text-slate-100">{a.label}</div>
                    <div className="mt-0.5 text-xs text-slate-500">{a.desc}</div>
                  </div>
                </div>
              </motion.div>
            );
          })}
        </div>
      </Section>

      {/* Section 3: XGBoost Analysis */}
      <Section title="XGBoost Analysis" eyebrow="03 · ML Score" testId="section-xgboost">
        <div className="grid grid-cols-1 items-center gap-8 md:grid-cols-2">
          <div className="flex justify-center">
            <RadialGauge
              value={tx.fraudProb}
              label="Fraud Probability"
              sublabel={`Confidence · ${tx.confidence}%`}
              color={tx.riskLevel === "critical" ? "red" : tx.riskLevel === "medium" ? "amber" : "emerald"}
              size={260}
              testId="xgboost-gauge"
            />
          </div>
          <div className="space-y-3">
            <h3 className="text-sm font-medium text-slate-300">Top Feature Contributions</h3>
            {[
              { name: "merchant_risk_score", value: 0.34, color: "#EF4444" },
              { name: "amount_zscore", value: 0.28, color: "#EF4444" },
              { name: "device_first_seen", value: 0.19, color: "#F59E0B" },
              { name: "geo_distance_24h", value: 0.13, color: "#F59E0B" },
              { name: "velocity_60s", value: 0.06, color: "#8B5CF6" },
            ].map((f) => (
              <div key={f.name}>
                <div className="flex items-baseline justify-between font-mono text-[11px]">
                  <span className="text-slate-400">{f.name}</span>
                  <span className="text-slate-200">{f.value.toFixed(2)}</span>
                </div>
                <div className="mt-1.5 h-1.5 overflow-hidden rounded-full bg-[#0B0F19] ring-1 ring-inset ring-white/[0.04]">
                  <motion.div
                    initial={{ width: 0 }}
                    animate={{ width: `${f.value * 100}%` }}
                    transition={{ duration: 1, delay: 0.3 }}
                    className="h-full rounded-full"
                    style={{ background: f.color, boxShadow: `0 0 6px ${f.color}60` }}
                  />
                </div>
              </div>
            ))}
            <div className="mt-4 rounded-md border border-[#1E2536] bg-[#0B0F19] p-3 font-mono text-[11px] text-slate-400">
              <span className="text-slate-500">model · </span>otari-xgb-v4.2.1
              <span className="mx-2 text-slate-700">·</span>
              <span className="text-slate-500">trained · </span>2026-02-08
            </div>
          </div>
        </div>
      </Section>

      {/* Section 4: Otari Decision Engine */}
      <Section title="Otari Decision Engine" eyebrow="04 · Routing" testId="section-decision">
        <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
          {PIPELINES.map((p) => {
            const active = p.id === tx.pipeline;
            const Icon = p.icon;
            return (
              <motion.div
                key={p.id}
                initial={{ opacity: 0, y: 6 }}
                animate={{ opacity: 1, y: 0 }}
                data-testid={`decision-pipeline-${p.id}`}
                className={cn(
                  "relative overflow-hidden rounded-xl border p-5 transition-all duration-300",
                  active
                    ? "border-transparent bg-[#131A2A]"
                    : "border-[#1E2536] bg-[#111623]/60 opacity-60 hover:opacity-100"
                )}
                style={active ? {
                  boxShadow: `0 0 0 1px ${p.accent}55, 0 0 32px -8px ${p.accent}55, inset 0 0 24px -8px ${p.accent}30`,
                } : {}}
              >
                {active && (
                  <div
                    className="pointer-events-none absolute -top-20 -right-20 h-40 w-40 rounded-full blur-3xl"
                    style={{ background: `${p.accent}40` }}
                  />
                )}
                <div className="relative flex items-start justify-between">
                  <div className="flex items-center gap-3">
                    <div
                      className="grid h-10 w-10 place-items-center rounded-lg ring-1"
                      style={{
                        background: `${p.accent}14`,
                        borderColor: `${p.accent}30`,
                      }}
                    >
                      <Icon size={17} strokeWidth={1.6} style={{ color: p.accent }} />
                    </div>
                    <div>
                      <div
                        className="font-mono text-[10px] uppercase tracking-[0.2em]"
                        style={{ color: active ? p.accent : "#64748B" }}
                      >
                        {p.title}
                      </div>
                      <div className="text-sm font-medium text-slate-100">{p.label}</div>
                    </div>
                  </div>
                  {active && (
                    <span
                      className="rounded-sm px-2 py-0.5 font-mono text-[9px] uppercase tracking-widest"
                      style={{ background: `${p.accent}22`, color: p.accent }}
                    >
                      Selected
                    </span>
                  )}
                </div>
              </motion.div>
            );
          })}
        </div>

        <div className="mt-5 rounded-xl border border-[#1E2536] bg-[#0B0F19] p-5">
          <div className="font-mono text-[10px] uppercase tracking-[0.18em] text-slate-500">
            Why {activePipeline.title} was selected
          </div>
          <div className="mt-3 grid grid-cols-1 gap-2 md:grid-cols-3">
            {selectionReasons(tx).map((r) => (
              <div
                key={r}
                className="flex items-center gap-2 rounded-md border border-[#1E2536] bg-[#111623] px-3 py-2 text-xs text-slate-300"
              >
                <ChevronRight size={12} style={{ color: activePipeline.accent }} />
                {r}
              </div>
            ))}
          </div>
        </div>
      </Section>

      {/* Section 5: Pipeline Execution Timeline */}
      <Section title="Pipeline Execution Timeline" eyebrow="05 · Execution" testId="section-execution">
        <div className="rounded-xl border border-[#1E2536] bg-[#111623] p-6">
          <ExecutionTimeline pipeline={activePipeline} />
        </div>
      </Section>

      {/* Section 6: LLM Recommendation (Pipeline C only) */}
      {tx.pipeline === "C" && <LLMRecommendation tx={tx} />}

      {/* Section 7: Human Decision Panel (Pipeline C only) */}
      {tx.pipeline === "C" && (
        <Section title="Human Decision Panel" eyebrow="07 · Action" testId="section-human">
        <div className="rounded-xl border border-[#1E2536] bg-[#111623] p-6">
          <div className="grid grid-cols-2 gap-3 md:grid-cols-4">
            <ActionButton icon={CheckCircle2} label="Approve" color="#10B981" testId="action-approve" />
            <ActionButton icon={XCircle} label="Block" color="#EF4444" testId="action-block" />
            <ActionButton icon={KeyRound} label="Request OTP" color="#F59E0B" testId="action-otp" />
            <ActionButton icon={Edit3} label="Override" color="#8B5CF6" testId="action-override" />
          </div>
          <div className="mt-5">
            <label className="font-mono text-[10px] uppercase tracking-widest text-slate-500">
              Analyst notes
            </label>
            <textarea
              data-testid="analyst-notes"
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              rows={3}
              placeholder="Document the rationale for this decision (will be appended to the audit trail)…"
              className="mt-2 w-full resize-none rounded-md border border-[#1E2536] bg-[#0B0F19] px-3 py-2.5 font-mono text-xs text-slate-200 placeholder:text-slate-600 focus:border-purple-500/40 focus:outline-none"
            />
          </div>
          <div className="mt-4 flex items-center justify-between border-t border-[#1E2536] pt-4">
            <div className="flex items-center gap-2 text-xs text-slate-500">
              <div className="h-6 w-6 overflow-hidden rounded-full ring-1 ring-white/10">
                <img
                  src="https://images.unsplash.com/photo-1560250097-0b93528c311a?crop=entropy&cs=srgb&fm=jpg&w=64&q=80"
                  alt="analyst"
                  className="h-full w-full object-cover"
                />
              </div>
              Signed in as <span className="text-slate-200">M. Reyes</span> · L2 Fraud Analyst
            </div>
            <button
              data-testid="commit-decision"
              className="rounded-md bg-purple-600 px-4 py-2 text-xs font-medium text-white shadow-[0_0_24px_-8px_rgba(139,92,246,0.7)] transition-colors hover:bg-purple-500"
            >
              Commit Decision
            </button>
          </div>
        </div>
      </Section>
      )}

      {/* Section 8: Investigation Audit Timeline */}
      <Section title="Investigation Audit Timeline" eyebrow="08 · Audit" testId="section-audit">
        <AuditTimeline tx={tx} />
      </Section>
    </div>
  );
}

/* ---------- Sub components ---------- */

function Section({ title, eyebrow, children, testId }) {
  return (
    <section data-testid={testId}>
      <div className="mb-4 flex items-end justify-between">
        <div>
          <div className="font-mono text-[10px] uppercase tracking-[0.18em] text-purple-300">
            {eyebrow}
          </div>
          <h2 className="mt-1 text-xl font-medium tracking-tight text-white">{title}</h2>
        </div>
      </div>
      {children}
    </section>
  );
}

function Badge({ label, value, color }) {
  const map = {
    emerald: "text-emerald-300 ring-emerald-500/20 bg-emerald-500/10",
    red: "text-red-300 ring-red-500/30 bg-red-500/10",
    amber: "text-amber-300 ring-amber-500/30 bg-amber-500/10",
    purple: "text-purple-300 ring-purple-500/30 bg-purple-500/10",
  };
  return (
    <div className={cn("rounded-md px-3 py-2 ring-1", map[color])}>
      <div className="font-mono text-[9px] uppercase tracking-widest opacity-70">{label}</div>
      <div className="font-mono text-sm">{value}</div>
    </div>
  );
}

function OverviewItem({ icon: Icon, label, value, sub, mono }) {
  return (
    <div className="rounded-lg border border-[#1E2536] bg-[#111623] p-4">
      <div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-widest text-slate-500">
        <Icon size={12} strokeWidth={1.6} className="text-purple-300" />
        {label}
      </div>
      <div className={cn("mt-2 truncate text-sm text-white", mono && "font-mono")}>{value}</div>
      {sub && <div className="mt-0.5 truncate font-mono text-[10px] text-slate-500">{sub}</div>}
    </div>
  );
}

function selectionReasons(tx) {
  if (tx.pipeline === "C") {
    return [
      `Fraud probability ${tx.fraudProb}% > 80% threshold`,
      `${tx.anomalies.length} behavioural anomalies detected`,
      `Transaction value ($${tx.amount.toLocaleString(undefined, { maximumFractionDigits: 0 })}) above review limit`,
    ];
  }
  if (tx.pipeline === "B") {
    return [
      `Fraud probability ${tx.fraudProb}% in 30-80% band`,
      `${tx.anomalies.length} medium-severity signals`,
      "Step-up authentication available for customer",
    ];
  }
  return [
    `Fraud probability ${tx.fraudProb}% below 30% threshold`,
    "No critical behavioural anomalies",
    "Customer profile is well-established",
  ];
}

function ExecutionTimeline({ pipeline }) {
  return (
    <div className="relative space-y-3">
      {pipeline.steps.map((step, i) => {
        const last = i === pipeline.steps.length - 1;
        return (
          <div key={step} className="relative flex items-start gap-4">
            {!last && (
              <div
                className="absolute left-[15px] top-9 bottom-[-12px] w-px"
                style={{ background: `linear-gradient(to bottom, ${pipeline.accent}55, transparent)` }}
              />
            )}
            <motion.div
              initial={{ scale: 0.6, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              transition={{ delay: i * 0.12 }}
              className="relative z-10 grid h-8 w-8 shrink-0 place-items-center rounded-full ring-1"
              style={{
                background: `${pipeline.accent}18`,
                borderColor: `${pipeline.accent}55`,
                color: pipeline.accent,
                boxShadow: i === pipeline.steps.length - 1 ? `0 0 16px ${pipeline.accent}80` : "",
              }}
            >
              <span className="font-mono text-[11px]">{i + 1}</span>
            </motion.div>
            <motion.div
              initial={{ opacity: 0, x: -4 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: i * 0.12 + 0.05 }}
              className="flex-1 rounded-md border border-[#1E2536] bg-[#0B0F19] px-4 py-3"
            >
              <div className="flex items-center justify-between">
                <div className="text-sm text-slate-100">{step}</div>
                <div className="font-mono text-[10px] text-slate-500">
                  {i === pipeline.steps.length - 1 ? "Pending" : `+${(i + 1) * 47}ms`}
                </div>
              </div>
            </motion.div>
          </div>
        );
      })}
    </div>
  );
}

function LLMRecommendation({ tx }) {
  return (
    <Section title="LLM Recommendation" eyebrow="06 · Reasoning" testId="section-llm">
      <div
        className="relative overflow-hidden rounded-xl border border-purple-500/30 bg-[#131A2A] p-6"
        style={{
          boxShadow: "0 0 0 1px rgba(139,92,246,0.25), 0 0 40px -8px rgba(139,92,246,0.4)",
        }}
      >
        <div className="pointer-events-none absolute -top-32 -right-32 h-64 w-64 rounded-full bg-purple-500/20 blur-3xl" />
        <div className="relative flex items-start justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="grid h-10 w-10 place-items-center rounded-md bg-purple-500/15 ring-1 ring-purple-500/30">
              <Cpu size={17} strokeWidth={1.6} className="text-purple-300" />
            </div>
            <div>
              <div className="font-mono text-[10px] uppercase tracking-[0.18em] text-purple-300">
                {LLM_RECOMMENDATION.model}
              </div>
              <div className="text-base font-medium text-white">{LLM_RECOMMENDATION.action}</div>
            </div>
          </div>
          <div className="text-right">
            <div className="font-mono text-[10px] uppercase tracking-widest text-slate-500">Confidence</div>
            <div className="font-mono text-2xl text-white">{LLM_RECOMMENDATION.confidence}%</div>
          </div>
        </div>

        <div className="relative mt-5 space-y-3">
          <div className="font-mono text-[10px] uppercase tracking-widest text-slate-500">Reasoning</div>
          {LLM_RECOMMENDATION.reasoning.map((r, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, x: -4 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: i * 0.08 }}
              className="flex gap-3 rounded-md border border-[#1E2536] bg-[#0B0F19]/60 p-3 text-sm leading-relaxed text-slate-300"
            >
              <span className="font-mono text-[10px] text-purple-300">[{i + 1}]</span>
              <span>{r}</span>
            </motion.div>
          ))}
        </div>

        <div className="relative mt-5 grid grid-cols-1 gap-3 md:grid-cols-2">
          <div className="rounded-md border border-[#1E2536] bg-[#0B0F19]/60 p-4">
            <div className="font-mono text-[10px] uppercase tracking-widest text-slate-500">
              Suggested next step
            </div>
            <div className="mt-1.5 text-sm text-slate-200">{LLM_RECOMMENDATION.nextStep}</div>
          </div>
          <div className="rounded-md border border-[#1E2536] bg-[#0B0F19]/60 p-4 font-mono text-xs text-slate-400">
            <div className="flex justify-between">
              <span className="text-slate-500">tokens</span>
              <span>{LLM_RECOMMENDATION.tokens.toLocaleString()}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-500">latency</span>
              <span>{LLM_RECOMMENDATION.latencyMs}ms</span>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-500">cost</span>
              <span>$0.0342</span>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-500">audit hash</span>
              <span>0x84a…f2c1</span>
            </div>
          </div>
        </div>
      </div>
    </Section>
  );
}

function ActionButton({ icon: Icon, label, color, testId }) {
  return (
    <button
      data-testid={testId}
      className="group relative flex flex-col items-start gap-3 overflow-hidden rounded-lg border border-[#1E2536] bg-[#0B0F19] p-4 text-left transition-all hover:border-[#2A3441] hover:bg-[#131A2A]"
      style={{ "--c": color }}
    >
      <div
        className="grid h-9 w-9 place-items-center rounded-md ring-1 transition-all"
        style={{ background: `${color}14`, color, borderColor: `${color}30` }}
      >
        <Icon size={16} strokeWidth={1.7} />
      </div>
      <div className="text-sm font-medium text-slate-100">{label}</div>
      <div
        className="pointer-events-none absolute inset-x-0 bottom-0 h-px opacity-0 transition-opacity group-hover:opacity-100"
        style={{ background: `linear-gradient(90deg, transparent, ${color}, transparent)` }}
      />
    </button>
  );
}

function AuditTimeline({ tx }) {
  const steps = [
    { label: "Transaction Received", detail: "Ingested from gateway", time: "T+0ms", icon: Inbox, color: "#06B6D4" },
    { label: "Data Transformation", detail: "Normalized · feature-store v9", time: "T+8ms", icon: Activity, color: "#06B6D4" },
    { label: "Fraud Probability Calculated", detail: `XGBoost score · ${tx.fraudProb}%`, time: "T+42ms", icon: Cpu, color: "#8B5CF6" },
    { label: "Otari Pipeline Selected", detail: `Routed to Pipeline ${tx.pipeline}`, time: "T+44ms", icon: GitBranch, color: "#8B5CF6" },
  ];

  // Isolation Forest runs only for B and C
  if (tx.pipeline === "B" || tx.pipeline === "C") {
    steps.push({
      label: "Isolation Forest",
      detail: tx.pipeline === "C"
        ? "Anomaly score 0.81 · strong outlier"
        : "Anomaly score 0.48 · borderline outlier",
      time: "T+71ms",
      icon: Activity,
      color: "#06B6D4",
    });
  }

  if (tx.pipeline === "A") {
    steps.push({
      label: "Auto-Approved",
      detail: "Low risk · no challenge required",
      time: "T+96ms",
      icon: CheckCircle2,
      color: "#10B981",
    });
  } else if (tx.pipeline === "B") {
    steps.push(
      {
        label: "OTP Recommended",
        detail: "Step-up challenge dispatched to customer",
        time: "T+118ms",
        icon: Sparkles,
        color: "#F59E0B",
      },
      {
        label: "Approved",
        detail: "OTP verified · transaction released",
        time: "T+4.2s",
        icon: CheckCircle2,
        color: "#10B981",
      },
    );
  } else {
    steps.push(
      {
        label: "LLM Recommendation",
        detail: "claude-sonnet-4.5 produced block recommendation",
        time: "T+1.84s",
        icon: Cpu,
        color: "#8B5CF6",
      },
      {
        label: "Human Review",
        detail: "Awaiting L2 analyst decision",
        time: "Pending",
        icon: Sparkles,
        color: "#F59E0B",
      },
      {
        label: "Final Decision",
        detail: "Pending analyst commit",
        time: "Pending",
        icon: CheckCircle2,
        color: "#10B981",
      },
    );
  }

  return (
    <div className="rounded-xl border border-[#1E2536] bg-[#111623] p-6">
      <div className="relative space-y-4">
        <div className="absolute left-[17px] top-3 bottom-3 w-px bg-gradient-to-b from-cyan-500/40 via-purple-500/40 to-emerald-500/40" />
        {steps.map((s, i) => {
          const Icon = s.icon;
          return (
            <motion.div
              key={s.label}
              initial={{ opacity: 0, x: -6 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: i * 0.08 }}
              className="relative flex items-start gap-4"
            >
              <div
                className="relative z-10 grid h-9 w-9 shrink-0 place-items-center rounded-full ring-1"
                style={{
                  background: `${s.color}14`,
                  borderColor: `${s.color}45`,
                  color: s.color,
                }}
              >
                <Icon size={14} strokeWidth={1.6} />
              </div>
              <div className="flex-1 rounded-md border border-[#1E2536] bg-[#0B0F19] p-3">
                <div className="flex items-baseline justify-between gap-3">
                  <div className="text-sm text-slate-100">{s.label}</div>
                  <div className="font-mono text-[10px] uppercase tracking-widest text-slate-500">{s.time}</div>
                </div>
                <div className="mt-0.5 font-mono text-[11px] text-slate-500">{s.detail}</div>
              </div>
            </motion.div>
          );
        })}
      </div>
    </div>
  );
}
